name: Arduino-Build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        fqbn:
          - esp32:esp32:featheresp32
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - imagiSat
          libraries: | 
            - name: Adafruit_GFX
            - name: Adafruit_BME680
            - name: Adafruit_NeoPixel
            - name: SparkFun_u-blox_GNSS_Arduino_Library
            - name: IridiumSBD
            - name: SoarkFun_AS3935
            - name: Adafruit_EPD
          cli-compile-flags: |
            - --warnings="none"