name: build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runs: [src/imagisat.ino, test]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Install Project Dependencies
      run: pio pkg install --global

    - name: Run PlatformIO build
      run: pio ci --project-conf -e featheresp32
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.runs }}

    - name: Code static analysis
      run: pio check
